-- RP World Maps package 06: characters DB stale instance-state cleanup (apply).
-- Generated by tools/character-openworld-migrate/generate_sql.py.
-- Source: tools/map-openworld-hotfix/golden/inventory.json (539 target maps).
-- Explicitly excluded by the frozen inventory: PvP, Arena, Housing map 2783 and all non-target maps.
-- Run against the `characters` database with worldserver stopped and a verified DB backup.
SET NAMES utf8mb4;


SET @rps_add_flags4 = (
  SELECT IF(
    COUNT(*) = 0,
    'ALTER TABLE `characters` ADD COLUMN `flags4` INT UNSIGNED NOT NULL DEFAULT 0 AFTER `timerunningSeasonId`',
    'SELECT 1'
  )
  FROM `information_schema`.`COLUMNS`
  WHERE `TABLE_SCHEMA` = DATABASE()
    AND `TABLE_NAME` = 'characters'
    AND `COLUMN_NAME` = 'flags4'
);
PREPARE rps_flags4_stmt FROM @rps_add_flags4;
EXECUTE rps_flags4_stmt;
DEALLOCATE PREPARE rps_flags4_stmt;

DROP TEMPORARY TABLE IF EXISTS `rps_openworld_target_map_20260808`;
CREATE TEMPORARY TABLE `rps_openworld_target_map_20260808` (
  `map_id` int unsigned NOT NULL,
  PRIMARY KEY (`map_id`)
) ENGINE=Memory;
INSERT INTO `rps_openworld_target_map_20260808` (`map_id`) VALUES
  (33),
  (34),
  (36),
  (43),
  (47),
  (48),
  (70),
  (90),
  (109),
  (129),
  (169),
  (189),
  (209),
  (229),
  (230),
  (249),
  (269),
  (289),
  (309),
  (329),
  (349),
  (389),
  (409),
  (429),
  (469),
  (509),
  (531),
  (532),
  (533),
  (534),
  (540),
  (542),
  (543),
  (544),
  (545),
  (546),
  (547),
  (548),
  (550),
  (552),
  (553),
  (554),
  (555),
  (556),
  (557),
  (558),
  (560),
  (564),
  (565),
  (568),
  (574),
  (575),
  (576),
  (578),
  (580),
  (585),
  (595),
  (599),
  (600),
  (601),
  (602),
  (603),
  (604),
  (608),
  (615),
  (616),
  (619),
  (624),
  (627),
  (631),
  (632),
  (637),
  (643),
  (644),
  (645),
  (649),
  (650),
  (657),
  (658),
  (668),
  (669),
  (670),
  (671),
  (720),
  (721),
  (724),
  (725),
  (734),
  (754),
  (755),
  (757),
  (859),
  (930),
  (938),
  (939),
  (940),
  (951),
  (959),
  (960),
  (961),
  (962),
  (967),
  (977),
  (994),
  (995),
  (996),
  (999),
  (1000),
  (1001),
  (1004),
  (1005),
  (1007),
  (1008),
  (1009),
  (1011),
  (1014),
  (1024),
  (1028),
  (1029),
  (1030),
  (1031),
  (1032),
  (1035),
  (1048),
  (1049),
  (1050),
  (1051),
  (1095),
  (1098),
  (1099),
  (1102),
  (1103),
  (1104),
  (1112),
  (1122),
  (1123),
  (1124),
  (1125),
  (1126),
  (1127),
  (1130),
  (1131),
  (1135),
  (1136),
  (1144),
  (1148),
  (1152),
  (1153),
  (1154),
  (1155),
  (1157),
  (1158),
  (1159),
  (1160),
  (1161),
  (1168),
  (1175),
  (1176),
  (1182),
  (1187),
  (1188),
  (1189),
  (1195),
  (1200),
  (1203),
  (1205),
  (1207),
  (1208),
  (1209),
  (1228),
  (1232),
  (1233),
  (1234),
  (1235),
  (1236),
  (1237),
  (1238),
  (1239),
  (1240),
  (1241),
  (1242),
  (1243),
  (1244),
  (1245),
  (1266),
  (1268),
  (1277),
  (1279),
  (1329),
  (1330),
  (1331),
  (1358),
  (1374),
  (1402),
  (1431),
  (1448),
  (1451),
  (1453),
  (1454),
  (1455),
  (1456),
  (1458),
  (1460),
  (1461),
  (1466),
  (1475),
  (1477),
  (1478),
  (1480),
  (1489),
  (1492),
  (1493),
  (1494),
  (1495),
  (1498),
  (1500),
  (1501),
  (1503),
  (1511),
  (1516),
  (1520),
  (1522),
  (1523),
  (1526),
  (1528),
  (1529),
  (1530),
  (1533),
  (1534),
  (1535),
  (1536),
  (1539),
  (1541),
  (1544),
  (1545),
  (1553),
  (1554),
  (1557),
  (1571),
  (1572),
  (1579),
  (1580),
  (1582),
  (1583),
  (1592),
  (1594),
  (1599),
  (1600),
  (1603),
  (1607),
  (1609),
  (1610),
  (1611),
  (1612),
  (1616),
  (1617),
  (1620),
  (1621),
  (1622),
  (1623),
  (1624),
  (1625),
  (1626),
  (1629),
  (1630),
  (1632),
  (1646),
  (1648),
  (1651),
  (1653),
  (1662),
  (1666),
  (1667),
  (1668),
  (1673),
  (1676),
  (1677),
  (1683),
  (1684),
  (1687),
  (1688),
  (1689),
  (1693),
  (1694),
  (1695),
  (1698),
  (1702),
  (1703),
  (1704),
  (1705),
  (1706),
  (1707),
  (1708),
  (1710),
  (1712),
  (1714),
  (1719),
  (1723),
  (1728),
  (1729),
  (1730),
  (1731),
  (1732),
  (1733),
  (1734),
  (1735),
  (1736),
  (1737),
  (1738),
  (1744),
  (1746),
  (1753),
  (1754),
  (1756),
  (1760),
  (1762),
  (1763),
  (1764),
  (1771),
  (1774),
  (1812),
  (1813),
  (1814),
  (1818),
  (1822),
  (1840),
  (1841),
  (1861),
  (1862),
  (1864),
  (1876),
  (1877),
  (1879),
  (1882),
  (1883),
  (1884),
  (1892),
  (1893),
  (1897),
  (1898),
  (1904),
  (1906),
  (1907),
  (1917),
  (1932),
  (1943),
  (1944),
  (1949),
  (1950),
  (1955),
  (2070),
  (2076),
  (2096),
  (2097),
  (2105),
  (2111),
  (2115),
  (2124),
  (2125),
  (2134),
  (2155),
  (2161),
  (2162),
  (2163),
  (2164),
  (2169),
  (2170),
  (2174),
  (2178),
  (2179),
  (2180),
  (2187),
  (2193),
  (2207),
  (2208),
  (2209),
  (2210),
  (2211),
  (2212),
  (2213),
  (2214),
  (2217),
  (2223),
  (2232),
  (2233),
  (2235),
  (2236),
  (2247),
  (2257),
  (2258),
  (2264),
  (2266),
  (2278),
  (2282),
  (2284),
  (2285),
  (2286),
  (2287),
  (2289),
  (2290),
  (2291),
  (2293),
  (2294),
  (2296),
  (2299),
  (2300),
  (2303),
  (2304),
  (2305),
  (2308),
  (2354),
  (2356),
  (2360),
  (2362),
  (2363),
  (2371),
  (2375),
  (2441),
  (2450),
  (2451),
  (2464),
  (2465),
  (2471),
  (2481),
  (2504),
  (2515),
  (2516),
  (2519),
  (2520),
  (2521),
  (2522),
  (2526),
  (2527),
  (2549),
  (2556),
  (2559),
  (2569),
  (2574),
  (2579),
  (2582),
  (2583),
  (2586),
  (2587),
  (2590),
  (2593),
  (2594),
  (2595),
  (2597),
  (2598),
  (2599),
  (2600),
  (2614),
  (2625),
  (2634),
  (2635),
  (2639),
  (2644),
  (2645),
  (2648),
  (2649),
  (2651),
  (2652),
  (2653),
  (2654),
  (2657),
  (2660),
  (2661),
  (2662),
  (2664),
  (2669),
  (2679),
  (2680),
  (2681),
  (2682),
  (2683),
  (2684),
  (2685),
  (2686),
  (2687),
  (2688),
  (2689),
  (2690),
  (2692),
  (2699),
  (2710),
  (2713),
  (2716),
  (2767),
  (2768),
  (2769),
  (2773),
  (2774),
  (2776),
  (2779),
  (2792),
  (2803),
  (2805),
  (2810),
  (2811),
  (2813),
  (2815),
  (2819),
  (2825),
  (2826),
  (2827),
  (2828),
  (2830),
  (2831),
  (2836),
  (2849),
  (2859),
  (2874),
  (2907),
  (2912),
  (2913),
  (2915),
  (2923),
  (2928),
  (2930),
  (2933),
  (2939),
  (2950),
  (2951),
  (2952),
  (2953),
  (2961),
  (2962),
  (2963),
  (2964),
  (2965),
  (2966),
  (2972),
  (2979),
  (3003),
  (3009),
  (3014),
  (3022),
  (3029),
  (3074);

SELECT 'target_map_count' AS `check`, COUNT(*) AS `actual`, 539 AS `expected`
FROM `rps_openworld_target_map_20260808`;

-- Archive tables retain a pre-image for operator audit after apply.
-- Recovery is from a verified characters DB backup, not from generated rollback SQL.
-- CREATE TABLE is DDL and commits in MySQL; all copied and mutated rows below are
-- protected by the following transaction.
CREATE TABLE IF NOT EXISTS `rps_openworld_20260808_character_instance_lock` LIKE `character_instance_lock`;
CREATE TABLE IF NOT EXISTS `rps_openworld_20260808_account_instance_times` LIKE `account_instance_times`;
CREATE TABLE IF NOT EXISTS `rps_openworld_20260808_respawn` LIKE `respawn`;
CREATE TABLE IF NOT EXISTS `rps_openworld_20260808_instance` LIKE `instance`;
CREATE TABLE IF NOT EXISTS `rps_openworld_20260808_characters` LIKE `characters`;
CREATE TABLE IF NOT EXISTS `rps_openworld_20260808_corpse` LIKE `corpse`;

START TRANSACTION;

-- Snapshot target instance IDs before deleting their target-map locks.
DROP TEMPORARY TABLE IF EXISTS `rps_openworld_target_instance_20260808`;
CREATE TEMPORARY TABLE `rps_openworld_target_instance_20260808` (
  `instance_id` int unsigned NOT NULL,
  PRIMARY KEY (`instance_id`)
) ENGINE=Memory;
INSERT INTO `rps_openworld_target_instance_20260808` (`instance_id`)
SELECT DISTINCT cil.`instanceId`
FROM `character_instance_lock` AS cil
JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = cil.`mapId`
WHERE cil.`instanceId` IS NOT NULL AND cil.`instanceId` <> 0;

INSERT IGNORE INTO `rps_openworld_target_instance_20260808` (`instance_id`)
SELECT DISTINCT c.`instance_id`
FROM `characters` AS c
JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = c.`map`
WHERE c.`instance_id` <> 0;

INSERT IGNORE INTO `rps_openworld_target_instance_20260808` (`instance_id`)
SELECT DISTINCT co.`instanceId`
FROM `corpse` AS co
JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = co.`mapId`
WHERE co.`instanceId` <> 0;

INSERT IGNORE INTO `rps_openworld_target_instance_20260808` (`instance_id`)
SELECT DISTINCT r.`instanceId`
FROM `respawn` AS r
JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = r.`mapId`
WHERE r.`instanceId` <> 0;

-- Only delete a parent when no non-target lock still refers to it.
DROP TEMPORARY TABLE IF EXISTS `rps_openworld_delete_instance_20260808`;
CREATE TEMPORARY TABLE `rps_openworld_delete_instance_20260808` (
  `instance_id` int unsigned NOT NULL,
  PRIMARY KEY (`instance_id`)
) ENGINE=Memory;
INSERT INTO `rps_openworld_delete_instance_20260808` (`instance_id`)
SELECT ti.`instance_id`
FROM `rps_openworld_target_instance_20260808` AS ti
JOIN `instance` AS i ON i.`instanceId` = ti.`instance_id`;

DELETE di
FROM `rps_openworld_delete_instance_20260808` AS di
JOIN `character_instance_lock` AS cil ON cil.`instanceId` = di.`instance_id`
LEFT JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = cil.`mapId`
WHERE tm.`map_id` IS NULL;

DELETE di
FROM `rps_openworld_delete_instance_20260808` AS di
JOIN `characters` AS c ON c.`instance_id` = di.`instance_id`
LEFT JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = c.`map`
WHERE tm.`map_id` IS NULL;

DELETE di
FROM `rps_openworld_delete_instance_20260808` AS di
JOIN `respawn` AS r ON r.`instanceId` = di.`instance_id`
LEFT JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = r.`mapId`
WHERE tm.`map_id` IS NULL;

DELETE di
FROM `rps_openworld_delete_instance_20260808` AS di
JOIN `corpse` AS co ON co.`instanceId` = di.`instance_id`
LEFT JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = co.`mapId`
WHERE tm.`map_id` IS NULL;

-- Account release times have no map column. Remove them only for a deleted
-- target parent or an already-orphaned target parent; preserve the value when
-- a non-target lock is the reason a shared parent remains.
DROP TEMPORARY TABLE IF EXISTS `rps_openworld_cleanup_account_instance_20260808`;
CREATE TEMPORARY TABLE `rps_openworld_cleanup_account_instance_20260808` (
  `instance_id` int unsigned NOT NULL,
  PRIMARY KEY (`instance_id`)
) ENGINE=Memory;
INSERT INTO `rps_openworld_cleanup_account_instance_20260808` (`instance_id`)
SELECT ti.`instance_id`
FROM `rps_openworld_target_instance_20260808` AS ti
LEFT JOIN `instance` AS i ON i.`instanceId` = ti.`instance_id`
LEFT JOIN `rps_openworld_delete_instance_20260808` AS di ON di.`instance_id` = ti.`instance_id`
WHERE i.`instanceId` IS NULL OR di.`instance_id` IS NOT NULL;

-- Backup complete source rows (including each table's primary key) before mutation.
INSERT IGNORE INTO `rps_openworld_20260808_character_instance_lock`
SELECT cil.*
FROM `character_instance_lock` AS cil
JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = cil.`mapId`;

INSERT IGNORE INTO `rps_openworld_20260808_account_instance_times`
SELECT ait.*
FROM `account_instance_times` AS ait
JOIN `rps_openworld_cleanup_account_instance_20260808` AS ti ON ti.`instance_id` = ait.`instanceId`;

INSERT IGNORE INTO `rps_openworld_20260808_respawn`
SELECT r.*
FROM `respawn` AS r
JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = r.`mapId`;

INSERT IGNORE INTO `rps_openworld_20260808_instance`
SELECT i.*
FROM `instance` AS i
JOIN `rps_openworld_delete_instance_20260808` AS di ON di.`instance_id` = i.`instanceId`;

INSERT IGNORE INTO `rps_openworld_20260808_characters`
SELECT c.*
FROM `characters` AS c
WHERE c.`map` IN (SELECT `map_id` FROM `rps_openworld_target_map_20260808`)
   OR (c.`health` = 0 AND EXISTS (
       SELECT 1
       FROM `corpse` AS co
       JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = co.`mapId`
       WHERE co.`guid` = c.`guid`
   ));

INSERT IGNORE INTO `rps_openworld_20260808_corpse`
SELECT co.*
FROM `corpse` AS co
JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = co.`mapId`;

-- Delete children first. Account lock times and respawns are stale only where
-- their instance/map is in this target migration; non-target maps are untouched.
DELETE cil
FROM `character_instance_lock` AS cil
JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = cil.`mapId`;

DELETE ait
FROM `account_instance_times` AS ait
JOIN `rps_openworld_cleanup_account_instance_20260808` AS ti ON ti.`instance_id` = ait.`instanceId`;

DELETE r
FROM `respawn` AS r
JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = r.`mapId`;

-- Delete only now-unreferenced instance parents. A parent with a non-target
-- lock remains intact and is reported by the post-apply check queries.
DELETE i
FROM `instance` AS i
JOIN `rps_openworld_delete_instance_20260808` AS di ON di.`instance_id` = i.`instanceId`;

-- Target-map characters no longer carry an instance ID. 0x100 is
-- AT_LOGIN_RESURRECT (Player.h); it is ORed in only for affected dead players.
UPDATE `characters` AS c
SET c.`instance_id` = 0,
    c.`at_login` = CASE
      WHEN c.`health` = 0 THEN c.`at_login` | 0x100
      ELSE c.`at_login`
    END
WHERE c.`map` IN (SELECT `map_id` FROM `rps_openworld_target_map_20260808`);

UPDATE `characters` AS c
JOIN `corpse` AS co ON co.`guid` = c.`guid`
JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = co.`mapId`
SET c.`instance_id` = 0,
    c.`at_login` = c.`at_login` | 0x100
WHERE c.`health` = 0;

-- Corpses stay in place, but become world-instance corpses. Their phase and
-- customization children remain valid because the corpse row is not deleted.
UPDATE `corpse` AS co
JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = co.`mapId`
SET co.`instanceId` = 0;

COMMIT;

-- Post-apply target-scoped checks. Every `actual` must be 0, except the final
-- informational count of parents retained for still-existing non-target locks.
SELECT 'stale_character_instance_id' AS `check`, COUNT(*) AS `actual`
FROM `characters` AS c
JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = c.`map`
WHERE c.`instance_id` <> 0;

SELECT 'target_character_instance_lock' AS `check`, COUNT(*) AS `actual`
FROM `character_instance_lock` AS cil
JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = cil.`mapId`;

SELECT 'target_respawn' AS `check`, COUNT(*) AS `actual`
FROM `respawn` AS r
JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = r.`mapId`;

SELECT 'target_corpse_instance_id' AS `check`, COUNT(*) AS `actual`
FROM `corpse` AS co
JOIN `rps_openworld_target_map_20260808` AS tm ON tm.`map_id` = co.`mapId`
WHERE co.`instanceId` <> 0;

SELECT 'deletable_parent_left' AS `check`, COUNT(*) AS `actual`
FROM `instance` AS i
JOIN `rps_openworld_delete_instance_20260808` AS di ON di.`instance_id` = i.`instanceId`;

SELECT 'retained_parent_with_non_target_lock' AS `check`, COUNT(*) AS `actual`
FROM `instance` AS i
JOIN `rps_openworld_target_instance_20260808` AS ti ON ti.`instance_id` = i.`instanceId`;
