-- Generated by tools/world-openworld-migrate/world_spawns.py; do not edit manually.
-- Input: tools/map-openworld-hotfix/golden/inventory.json
-- Input SHA-256: 87de10705bf297e9b9cd7b3b0a34f11ca2277f7caabb1f193fe17f398a92c528
-- Target maps: 539
--
-- MAP_COMMON spawn migration. It changes only spawn difficulties, instance-bound
-- group activation, linked-respawn rows, and default creature difficulty rows.
-- It deliberately does not modify native phases, AIName, ScriptName, or loot.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS `rps_openworld_spawn_migration` (
  `migration_version` varchar(96) NOT NULL,
  `input_sha256` char(64) NOT NULL,
  `target_map_count` smallint unsigned NOT NULL,
  `applied_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`migration_version`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rps_openworld_spawn_target_map` (
  `migration_version` varchar(96) NOT NULL,
  `map_id` int unsigned NOT NULL,
  PRIMARY KEY (`migration_version`, `map_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rps_openworld_creature_spawn_snapshot` (
  `migration_version` varchar(96) NOT NULL,
  `guid` bigint unsigned NOT NULL,
  `map_id` int unsigned NOT NULL,
  `spawn_difficulties` varchar(100) NOT NULL,
  PRIMARY KEY (`migration_version`, `guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rps_openworld_gameobject_spawn_snapshot` (
  `migration_version` varchar(96) NOT NULL,
  `guid` bigint unsigned NOT NULL,
  `map_id` int unsigned NOT NULL,
  `spawn_difficulties` varchar(100) NOT NULL,
  PRIMARY KEY (`migration_version`, `guid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rps_openworld_areatrigger_spawn_snapshot` (
  `migration_version` varchar(96) NOT NULL,
  `spawn_id` bigint unsigned NOT NULL,
  `map_id` int unsigned NOT NULL,
  `spawn_difficulties` varchar(100) NOT NULL,
  PRIMARY KEY (`migration_version`, `spawn_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rps_openworld_instance_spawn_group_snapshot` (
  `migration_version` varchar(96) NOT NULL,
  `instance_map_id` smallint unsigned NOT NULL,
  `boss_state_id` tinyint unsigned NOT NULL,
  `boss_states` tinyint unsigned NOT NULL,
  `spawn_group_id` int unsigned NOT NULL,
  `flags` tinyint unsigned NOT NULL,
  PRIMARY KEY (`migration_version`, `instance_map_id`, `boss_state_id`, `spawn_group_id`, `boss_states`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rps_openworld_spawn_group_template_snapshot` (
  `migration_version` varchar(96) NOT NULL,
  `group_id` int unsigned NOT NULL,
  `group_flags` int unsigned NOT NULL,
  PRIMARY KEY (`migration_version`, `group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rps_openworld_manual_spawn_group_audit` (
  `migration_version` varchar(96) NOT NULL,
  `group_id` int unsigned NOT NULL,
  `group_name` varchar(100) NOT NULL,
  `original_group_flags` int unsigned NOT NULL,
  `target_member_count` int unsigned NOT NULL,
  `non_target_member_count` int unsigned NOT NULL,
  `unresolved_member_count` int unsigned NOT NULL,
  `eligible_for_auto_enable` tinyint unsigned NOT NULL,
  PRIMARY KEY (`migration_version`, `group_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rps_openworld_linked_respawn_archive` (
  `migration_version` varchar(96) NOT NULL,
  `guid` bigint unsigned NOT NULL,
  `linked_guid` bigint unsigned NOT NULL,
  `link_type` tinyint unsigned NOT NULL,
  PRIMARY KEY (`migration_version`, `guid`, `link_type`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `rps_openworld_template_difficulty_snapshot` (
  `migration_version` varchar(96) NOT NULL,
  `entry` int unsigned NOT NULL,
  `source_difficulty_id` int NULL,
  `source_kind` varchar(40) NOT NULL,
  `created_difficulty_zero` tinyint unsigned NOT NULL DEFAULT 0,
  PRIMARY KEY (`migration_version`, `entry`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

DROP PROCEDURE IF EXISTS `rps_openworld_assert_apply`;
DELIMITER //
CREATE PROCEDURE `rps_openworld_assert_apply`()
BEGIN
  IF EXISTS (
    SELECT 1
    FROM `rps_openworld_spawn_migration`
    WHERE `migration_version` = '2026_08_08_00_map_openworld_spawns'
      AND `input_sha256` <> '87de10705bf297e9b9cd7b3b0a34f11ca2277f7caabb1f193fe17f398a92c528'
  ) THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'RPS openworld spawn migration inventory SHA mismatch';
  END IF;
END//
DELIMITER ;
CALL `rps_openworld_assert_apply`();
DROP PROCEDURE `rps_openworld_assert_apply`;

INSERT IGNORE INTO `rps_openworld_spawn_target_map` (`migration_version`, `map_id`) VALUES
  ('2026_08_08_00_map_openworld_spawns', 33),
  ('2026_08_08_00_map_openworld_spawns', 34),
  ('2026_08_08_00_map_openworld_spawns', 36),
  ('2026_08_08_00_map_openworld_spawns', 43),
  ('2026_08_08_00_map_openworld_spawns', 47),
  ('2026_08_08_00_map_openworld_spawns', 48),
  ('2026_08_08_00_map_openworld_spawns', 70),
  ('2026_08_08_00_map_openworld_spawns', 90),
  ('2026_08_08_00_map_openworld_spawns', 109),
  ('2026_08_08_00_map_openworld_spawns', 129),
  ('2026_08_08_00_map_openworld_spawns', 169),
  ('2026_08_08_00_map_openworld_spawns', 189),
  ('2026_08_08_00_map_openworld_spawns', 209),
  ('2026_08_08_00_map_openworld_spawns', 229),
  ('2026_08_08_00_map_openworld_spawns', 230),
  ('2026_08_08_00_map_openworld_spawns', 249),
  ('2026_08_08_00_map_openworld_spawns', 269),
  ('2026_08_08_00_map_openworld_spawns', 289),
  ('2026_08_08_00_map_openworld_spawns', 309),
  ('2026_08_08_00_map_openworld_spawns', 329),
  ('2026_08_08_00_map_openworld_spawns', 349),
  ('2026_08_08_00_map_openworld_spawns', 389),
  ('2026_08_08_00_map_openworld_spawns', 409),
  ('2026_08_08_00_map_openworld_spawns', 429),
  ('2026_08_08_00_map_openworld_spawns', 469),
  ('2026_08_08_00_map_openworld_spawns', 509),
  ('2026_08_08_00_map_openworld_spawns', 531),
  ('2026_08_08_00_map_openworld_spawns', 532),
  ('2026_08_08_00_map_openworld_spawns', 533),
  ('2026_08_08_00_map_openworld_spawns', 534),
  ('2026_08_08_00_map_openworld_spawns', 540),
  ('2026_08_08_00_map_openworld_spawns', 542),
  ('2026_08_08_00_map_openworld_spawns', 543),
  ('2026_08_08_00_map_openworld_spawns', 544),
  ('2026_08_08_00_map_openworld_spawns', 545),
  ('2026_08_08_00_map_openworld_spawns', 546),
  ('2026_08_08_00_map_openworld_spawns', 547),
  ('2026_08_08_00_map_openworld_spawns', 548),
  ('2026_08_08_00_map_openworld_spawns', 550),
  ('2026_08_08_00_map_openworld_spawns', 552),
  ('2026_08_08_00_map_openworld_spawns', 553),
  ('2026_08_08_00_map_openworld_spawns', 554),
  ('2026_08_08_00_map_openworld_spawns', 555),
  ('2026_08_08_00_map_openworld_spawns', 556),
  ('2026_08_08_00_map_openworld_spawns', 557),
  ('2026_08_08_00_map_openworld_spawns', 558),
  ('2026_08_08_00_map_openworld_spawns', 560),
  ('2026_08_08_00_map_openworld_spawns', 564),
  ('2026_08_08_00_map_openworld_spawns', 565),
  ('2026_08_08_00_map_openworld_spawns', 568),
  ('2026_08_08_00_map_openworld_spawns', 574),
  ('2026_08_08_00_map_openworld_spawns', 575),
  ('2026_08_08_00_map_openworld_spawns', 576),
  ('2026_08_08_00_map_openworld_spawns', 578),
  ('2026_08_08_00_map_openworld_spawns', 580),
  ('2026_08_08_00_map_openworld_spawns', 585),
  ('2026_08_08_00_map_openworld_spawns', 595),
  ('2026_08_08_00_map_openworld_spawns', 599),
  ('2026_08_08_00_map_openworld_spawns', 600),
  ('2026_08_08_00_map_openworld_spawns', 601),
  ('2026_08_08_00_map_openworld_spawns', 602),
  ('2026_08_08_00_map_openworld_spawns', 603),
  ('2026_08_08_00_map_openworld_spawns', 604),
  ('2026_08_08_00_map_openworld_spawns', 608),
  ('2026_08_08_00_map_openworld_spawns', 615),
  ('2026_08_08_00_map_openworld_spawns', 616),
  ('2026_08_08_00_map_openworld_spawns', 619),
  ('2026_08_08_00_map_openworld_spawns', 624),
  ('2026_08_08_00_map_openworld_spawns', 627),
  ('2026_08_08_00_map_openworld_spawns', 631),
  ('2026_08_08_00_map_openworld_spawns', 632),
  ('2026_08_08_00_map_openworld_spawns', 637),
  ('2026_08_08_00_map_openworld_spawns', 643),
  ('2026_08_08_00_map_openworld_spawns', 644),
  ('2026_08_08_00_map_openworld_spawns', 645),
  ('2026_08_08_00_map_openworld_spawns', 649),
  ('2026_08_08_00_map_openworld_spawns', 650),
  ('2026_08_08_00_map_openworld_spawns', 657),
  ('2026_08_08_00_map_openworld_spawns', 658),
  ('2026_08_08_00_map_openworld_spawns', 668),
  ('2026_08_08_00_map_openworld_spawns', 669),
  ('2026_08_08_00_map_openworld_spawns', 670),
  ('2026_08_08_00_map_openworld_spawns', 671),
  ('2026_08_08_00_map_openworld_spawns', 720),
  ('2026_08_08_00_map_openworld_spawns', 721),
  ('2026_08_08_00_map_openworld_spawns', 724),
  ('2026_08_08_00_map_openworld_spawns', 725),
  ('2026_08_08_00_map_openworld_spawns', 734),
  ('2026_08_08_00_map_openworld_spawns', 754),
  ('2026_08_08_00_map_openworld_spawns', 755),
  ('2026_08_08_00_map_openworld_spawns', 757),
  ('2026_08_08_00_map_openworld_spawns', 859),
  ('2026_08_08_00_map_openworld_spawns', 930),
  ('2026_08_08_00_map_openworld_spawns', 938),
  ('2026_08_08_00_map_openworld_spawns', 939),
  ('2026_08_08_00_map_openworld_spawns', 940),
  ('2026_08_08_00_map_openworld_spawns', 951),
  ('2026_08_08_00_map_openworld_spawns', 959),
  ('2026_08_08_00_map_openworld_spawns', 960),
  ('2026_08_08_00_map_openworld_spawns', 961),
  ('2026_08_08_00_map_openworld_spawns', 962),
  ('2026_08_08_00_map_openworld_spawns', 967),
  ('2026_08_08_00_map_openworld_spawns', 977),
  ('2026_08_08_00_map_openworld_spawns', 994),
  ('2026_08_08_00_map_openworld_spawns', 995),
  ('2026_08_08_00_map_openworld_spawns', 996),
  ('2026_08_08_00_map_openworld_spawns', 999),
  ('2026_08_08_00_map_openworld_spawns', 1000),
  ('2026_08_08_00_map_openworld_spawns', 1001),
  ('2026_08_08_00_map_openworld_spawns', 1004),
  ('2026_08_08_00_map_openworld_spawns', 1005),
  ('2026_08_08_00_map_openworld_spawns', 1007),
  ('2026_08_08_00_map_openworld_spawns', 1008),
  ('2026_08_08_00_map_openworld_spawns', 1009),
  ('2026_08_08_00_map_openworld_spawns', 1011),
  ('2026_08_08_00_map_openworld_spawns', 1014),
  ('2026_08_08_00_map_openworld_spawns', 1024),
  ('2026_08_08_00_map_openworld_spawns', 1028),
  ('2026_08_08_00_map_openworld_spawns', 1029),
  ('2026_08_08_00_map_openworld_spawns', 1030),
  ('2026_08_08_00_map_openworld_spawns', 1031),
  ('2026_08_08_00_map_openworld_spawns', 1032),
  ('2026_08_08_00_map_openworld_spawns', 1035),
  ('2026_08_08_00_map_openworld_spawns', 1048),
  ('2026_08_08_00_map_openworld_spawns', 1049),
  ('2026_08_08_00_map_openworld_spawns', 1050),
  ('2026_08_08_00_map_openworld_spawns', 1051),
  ('2026_08_08_00_map_openworld_spawns', 1095),
  ('2026_08_08_00_map_openworld_spawns', 1098),
  ('2026_08_08_00_map_openworld_spawns', 1099),
  ('2026_08_08_00_map_openworld_spawns', 1102),
  ('2026_08_08_00_map_openworld_spawns', 1103),
  ('2026_08_08_00_map_openworld_spawns', 1104),
  ('2026_08_08_00_map_openworld_spawns', 1112),
  ('2026_08_08_00_map_openworld_spawns', 1122),
  ('2026_08_08_00_map_openworld_spawns', 1123),
  ('2026_08_08_00_map_openworld_spawns', 1124),
  ('2026_08_08_00_map_openworld_spawns', 1125),
  ('2026_08_08_00_map_openworld_spawns', 1126),
  ('2026_08_08_00_map_openworld_spawns', 1127),
  ('2026_08_08_00_map_openworld_spawns', 1130),
  ('2026_08_08_00_map_openworld_spawns', 1131),
  ('2026_08_08_00_map_openworld_spawns', 1135),
  ('2026_08_08_00_map_openworld_spawns', 1136),
  ('2026_08_08_00_map_openworld_spawns', 1144),
  ('2026_08_08_00_map_openworld_spawns', 1148),
  ('2026_08_08_00_map_openworld_spawns', 1152),
  ('2026_08_08_00_map_openworld_spawns', 1153),
  ('2026_08_08_00_map_openworld_spawns', 1154),
  ('2026_08_08_00_map_openworld_spawns', 1155),
  ('2026_08_08_00_map_openworld_spawns', 1157),
  ('2026_08_08_00_map_openworld_spawns', 1158),
  ('2026_08_08_00_map_openworld_spawns', 1159),
  ('2026_08_08_00_map_openworld_spawns', 1160),
  ('2026_08_08_00_map_openworld_spawns', 1161),
  ('2026_08_08_00_map_openworld_spawns', 1168),
  ('2026_08_08_00_map_openworld_spawns', 1175),
  ('2026_08_08_00_map_openworld_spawns', 1176),
  ('2026_08_08_00_map_openworld_spawns', 1182),
  ('2026_08_08_00_map_openworld_spawns', 1187),
  ('2026_08_08_00_map_openworld_spawns', 1188),
  ('2026_08_08_00_map_openworld_spawns', 1189),
  ('2026_08_08_00_map_openworld_spawns', 1195),
  ('2026_08_08_00_map_openworld_spawns', 1200),
  ('2026_08_08_00_map_openworld_spawns', 1203),
  ('2026_08_08_00_map_openworld_spawns', 1205),
  ('2026_08_08_00_map_openworld_spawns', 1207),
  ('2026_08_08_00_map_openworld_spawns', 1208),
  ('2026_08_08_00_map_openworld_spawns', 1209),
  ('2026_08_08_00_map_openworld_spawns', 1228),
  ('2026_08_08_00_map_openworld_spawns', 1232),
  ('2026_08_08_00_map_openworld_spawns', 1233),
  ('2026_08_08_00_map_openworld_spawns', 1234),
  ('2026_08_08_00_map_openworld_spawns', 1235),
  ('2026_08_08_00_map_openworld_spawns', 1236),
  ('2026_08_08_00_map_openworld_spawns', 1237),
  ('2026_08_08_00_map_openworld_spawns', 1238),
  ('2026_08_08_00_map_openworld_spawns', 1239),
  ('2026_08_08_00_map_openworld_spawns', 1240),
  ('2026_08_08_00_map_openworld_spawns', 1241),
  ('2026_08_08_00_map_openworld_spawns', 1242),
  ('2026_08_08_00_map_openworld_spawns', 1243),
  ('2026_08_08_00_map_openworld_spawns', 1244),
  ('2026_08_08_00_map_openworld_spawns', 1245),
  ('2026_08_08_00_map_openworld_spawns', 1266),
  ('2026_08_08_00_map_openworld_spawns', 1268),
  ('2026_08_08_00_map_openworld_spawns', 1277),
  ('2026_08_08_00_map_openworld_spawns', 1279),
  ('2026_08_08_00_map_openworld_spawns', 1329),
  ('2026_08_08_00_map_openworld_spawns', 1330),
  ('2026_08_08_00_map_openworld_spawns', 1331),
  ('2026_08_08_00_map_openworld_spawns', 1358),
  ('2026_08_08_00_map_openworld_spawns', 1374),
  ('2026_08_08_00_map_openworld_spawns', 1402),
  ('2026_08_08_00_map_openworld_spawns', 1431),
  ('2026_08_08_00_map_openworld_spawns', 1448),
  ('2026_08_08_00_map_openworld_spawns', 1451),
  ('2026_08_08_00_map_openworld_spawns', 1453),
  ('2026_08_08_00_map_openworld_spawns', 1454),
  ('2026_08_08_00_map_openworld_spawns', 1455),
  ('2026_08_08_00_map_openworld_spawns', 1456),
  ('2026_08_08_00_map_openworld_spawns', 1458),
  ('2026_08_08_00_map_openworld_spawns', 1460),
  ('2026_08_08_00_map_openworld_spawns', 1461),
  ('2026_08_08_00_map_openworld_spawns', 1466),
  ('2026_08_08_00_map_openworld_spawns', 1475),
  ('2026_08_08_00_map_openworld_spawns', 1477),
  ('2026_08_08_00_map_openworld_spawns', 1478),
  ('2026_08_08_00_map_openworld_spawns', 1480),
  ('2026_08_08_00_map_openworld_spawns', 1489),
  ('2026_08_08_00_map_openworld_spawns', 1492),
  ('2026_08_08_00_map_openworld_spawns', 1493),
  ('2026_08_08_00_map_openworld_spawns', 1494),
  ('2026_08_08_00_map_openworld_spawns', 1495),
  ('2026_08_08_00_map_openworld_spawns', 1498),
  ('2026_08_08_00_map_openworld_spawns', 1500),
  ('2026_08_08_00_map_openworld_spawns', 1501),
  ('2026_08_08_00_map_openworld_spawns', 1503),
  ('2026_08_08_00_map_openworld_spawns', 1511),
  ('2026_08_08_00_map_openworld_spawns', 1516),
  ('2026_08_08_00_map_openworld_spawns', 1520),
  ('2026_08_08_00_map_openworld_spawns', 1522),
  ('2026_08_08_00_map_openworld_spawns', 1523),
  ('2026_08_08_00_map_openworld_spawns', 1526),
  ('2026_08_08_00_map_openworld_spawns', 1528),
  ('2026_08_08_00_map_openworld_spawns', 1529),
  ('2026_08_08_00_map_openworld_spawns', 1530),
  ('2026_08_08_00_map_openworld_spawns', 1533),
  ('2026_08_08_00_map_openworld_spawns', 1534),
  ('2026_08_08_00_map_openworld_spawns', 1535),
  ('2026_08_08_00_map_openworld_spawns', 1536),
  ('2026_08_08_00_map_openworld_spawns', 1539),
  ('2026_08_08_00_map_openworld_spawns', 1541),
  ('2026_08_08_00_map_openworld_spawns', 1544),
  ('2026_08_08_00_map_openworld_spawns', 1545),
  ('2026_08_08_00_map_openworld_spawns', 1553),
  ('2026_08_08_00_map_openworld_spawns', 1554),
  ('2026_08_08_00_map_openworld_spawns', 1557),
  ('2026_08_08_00_map_openworld_spawns', 1571),
  ('2026_08_08_00_map_openworld_spawns', 1572),
  ('2026_08_08_00_map_openworld_spawns', 1579),
  ('2026_08_08_00_map_openworld_spawns', 1580),
  ('2026_08_08_00_map_openworld_spawns', 1582),
  ('2026_08_08_00_map_openworld_spawns', 1583),
  ('2026_08_08_00_map_openworld_spawns', 1592),
  ('2026_08_08_00_map_openworld_spawns', 1594),
  ('2026_08_08_00_map_openworld_spawns', 1599),
  ('2026_08_08_00_map_openworld_spawns', 1600),
  ('2026_08_08_00_map_openworld_spawns', 1603),
  ('2026_08_08_00_map_openworld_spawns', 1607),
  ('2026_08_08_00_map_openworld_spawns', 1609),
  ('2026_08_08_00_map_openworld_spawns', 1610),
  ('2026_08_08_00_map_openworld_spawns', 1611),
  ('2026_08_08_00_map_openworld_spawns', 1612),
  ('2026_08_08_00_map_openworld_spawns', 1616),
  ('2026_08_08_00_map_openworld_spawns', 1617),
  ('2026_08_08_00_map_openworld_spawns', 1620),
  ('2026_08_08_00_map_openworld_spawns', 1621),
  ('2026_08_08_00_map_openworld_spawns', 1622),
  ('2026_08_08_00_map_openworld_spawns', 1623),
  ('2026_08_08_00_map_openworld_spawns', 1624),
  ('2026_08_08_00_map_openworld_spawns', 1625),
  ('2026_08_08_00_map_openworld_spawns', 1626),
  ('2026_08_08_00_map_openworld_spawns', 1629),
  ('2026_08_08_00_map_openworld_spawns', 1630),
  ('2026_08_08_00_map_openworld_spawns', 1632),
  ('2026_08_08_00_map_openworld_spawns', 1646),
  ('2026_08_08_00_map_openworld_spawns', 1648),
  ('2026_08_08_00_map_openworld_spawns', 1651),
  ('2026_08_08_00_map_openworld_spawns', 1653),
  ('2026_08_08_00_map_openworld_spawns', 1662),
  ('2026_08_08_00_map_openworld_spawns', 1666),
  ('2026_08_08_00_map_openworld_spawns', 1667),
  ('2026_08_08_00_map_openworld_spawns', 1668),
  ('2026_08_08_00_map_openworld_spawns', 1673),
  ('2026_08_08_00_map_openworld_spawns', 1676),
  ('2026_08_08_00_map_openworld_spawns', 1677),
  ('2026_08_08_00_map_openworld_spawns', 1683),
  ('2026_08_08_00_map_openworld_spawns', 1684),
  ('2026_08_08_00_map_openworld_spawns', 1687),
  ('2026_08_08_00_map_openworld_spawns', 1688),
  ('2026_08_08_00_map_openworld_spawns', 1689),
  ('2026_08_08_00_map_openworld_spawns', 1693),
  ('2026_08_08_00_map_openworld_spawns', 1694),
  ('2026_08_08_00_map_openworld_spawns', 1695),
  ('2026_08_08_00_map_openworld_spawns', 1698),
  ('2026_08_08_00_map_openworld_spawns', 1702),
  ('2026_08_08_00_map_openworld_spawns', 1703),
  ('2026_08_08_00_map_openworld_spawns', 1704),
  ('2026_08_08_00_map_openworld_spawns', 1705),
  ('2026_08_08_00_map_openworld_spawns', 1706),
  ('2026_08_08_00_map_openworld_spawns', 1707),
  ('2026_08_08_00_map_openworld_spawns', 1708),
  ('2026_08_08_00_map_openworld_spawns', 1710),
  ('2026_08_08_00_map_openworld_spawns', 1712),
  ('2026_08_08_00_map_openworld_spawns', 1714),
  ('2026_08_08_00_map_openworld_spawns', 1719),
  ('2026_08_08_00_map_openworld_spawns', 1723),
  ('2026_08_08_00_map_openworld_spawns', 1728),
  ('2026_08_08_00_map_openworld_spawns', 1729),
  ('2026_08_08_00_map_openworld_spawns', 1730),
  ('2026_08_08_00_map_openworld_spawns', 1731),
  ('2026_08_08_00_map_openworld_spawns', 1732),
  ('2026_08_08_00_map_openworld_spawns', 1733),
  ('2026_08_08_00_map_openworld_spawns', 1734),
  ('2026_08_08_00_map_openworld_spawns', 1735),
  ('2026_08_08_00_map_openworld_spawns', 1736),
  ('2026_08_08_00_map_openworld_spawns', 1737),
  ('2026_08_08_00_map_openworld_spawns', 1738),
  ('2026_08_08_00_map_openworld_spawns', 1744),
  ('2026_08_08_00_map_openworld_spawns', 1746),
  ('2026_08_08_00_map_openworld_spawns', 1753),
  ('2026_08_08_00_map_openworld_spawns', 1754),
  ('2026_08_08_00_map_openworld_spawns', 1756),
  ('2026_08_08_00_map_openworld_spawns', 1760),
  ('2026_08_08_00_map_openworld_spawns', 1762),
  ('2026_08_08_00_map_openworld_spawns', 1763),
  ('2026_08_08_00_map_openworld_spawns', 1764),
  ('2026_08_08_00_map_openworld_spawns', 1771),
  ('2026_08_08_00_map_openworld_spawns', 1774),
  ('2026_08_08_00_map_openworld_spawns', 1812),
  ('2026_08_08_00_map_openworld_spawns', 1813),
  ('2026_08_08_00_map_openworld_spawns', 1814),
  ('2026_08_08_00_map_openworld_spawns', 1818),
  ('2026_08_08_00_map_openworld_spawns', 1822),
  ('2026_08_08_00_map_openworld_spawns', 1840),
  ('2026_08_08_00_map_openworld_spawns', 1841),
  ('2026_08_08_00_map_openworld_spawns', 1861),
  ('2026_08_08_00_map_openworld_spawns', 1862),
  ('2026_08_08_00_map_openworld_spawns', 1864),
  ('2026_08_08_00_map_openworld_spawns', 1876),
  ('2026_08_08_00_map_openworld_spawns', 1877),
  ('2026_08_08_00_map_openworld_spawns', 1879),
  ('2026_08_08_00_map_openworld_spawns', 1882),
  ('2026_08_08_00_map_openworld_spawns', 1883),
  ('2026_08_08_00_map_openworld_spawns', 1884),
  ('2026_08_08_00_map_openworld_spawns', 1892),
  ('2026_08_08_00_map_openworld_spawns', 1893),
  ('2026_08_08_00_map_openworld_spawns', 1897),
  ('2026_08_08_00_map_openworld_spawns', 1898),
  ('2026_08_08_00_map_openworld_spawns', 1904),
  ('2026_08_08_00_map_openworld_spawns', 1906),
  ('2026_08_08_00_map_openworld_spawns', 1907),
  ('2026_08_08_00_map_openworld_spawns', 1917),
  ('2026_08_08_00_map_openworld_spawns', 1932),
  ('2026_08_08_00_map_openworld_spawns', 1943),
  ('2026_08_08_00_map_openworld_spawns', 1944),
  ('2026_08_08_00_map_openworld_spawns', 1949),
  ('2026_08_08_00_map_openworld_spawns', 1950),
  ('2026_08_08_00_map_openworld_spawns', 1955),
  ('2026_08_08_00_map_openworld_spawns', 2070),
  ('2026_08_08_00_map_openworld_spawns', 2076),
  ('2026_08_08_00_map_openworld_spawns', 2096),
  ('2026_08_08_00_map_openworld_spawns', 2097),
  ('2026_08_08_00_map_openworld_spawns', 2105),
  ('2026_08_08_00_map_openworld_spawns', 2111),
  ('2026_08_08_00_map_openworld_spawns', 2115),
  ('2026_08_08_00_map_openworld_spawns', 2124),
  ('2026_08_08_00_map_openworld_spawns', 2125),
  ('2026_08_08_00_map_openworld_spawns', 2134),
  ('2026_08_08_00_map_openworld_spawns', 2155),
  ('2026_08_08_00_map_openworld_spawns', 2161),
  ('2026_08_08_00_map_openworld_spawns', 2162),
  ('2026_08_08_00_map_openworld_spawns', 2163),
  ('2026_08_08_00_map_openworld_spawns', 2164),
  ('2026_08_08_00_map_openworld_spawns', 2169),
  ('2026_08_08_00_map_openworld_spawns', 2170),
  ('2026_08_08_00_map_openworld_spawns', 2174),
  ('2026_08_08_00_map_openworld_spawns', 2178),
  ('2026_08_08_00_map_openworld_spawns', 2179),
  ('2026_08_08_00_map_openworld_spawns', 2180),
  ('2026_08_08_00_map_openworld_spawns', 2187),
  ('2026_08_08_00_map_openworld_spawns', 2193),
  ('2026_08_08_00_map_openworld_spawns', 2207),
  ('2026_08_08_00_map_openworld_spawns', 2208),
  ('2026_08_08_00_map_openworld_spawns', 2209),
  ('2026_08_08_00_map_openworld_spawns', 2210),
  ('2026_08_08_00_map_openworld_spawns', 2211),
  ('2026_08_08_00_map_openworld_spawns', 2212),
  ('2026_08_08_00_map_openworld_spawns', 2213),
  ('2026_08_08_00_map_openworld_spawns', 2214),
  ('2026_08_08_00_map_openworld_spawns', 2217),
  ('2026_08_08_00_map_openworld_spawns', 2223),
  ('2026_08_08_00_map_openworld_spawns', 2232),
  ('2026_08_08_00_map_openworld_spawns', 2233),
  ('2026_08_08_00_map_openworld_spawns', 2235),
  ('2026_08_08_00_map_openworld_spawns', 2236),
  ('2026_08_08_00_map_openworld_spawns', 2247),
  ('2026_08_08_00_map_openworld_spawns', 2257),
  ('2026_08_08_00_map_openworld_spawns', 2258),
  ('2026_08_08_00_map_openworld_spawns', 2264),
  ('2026_08_08_00_map_openworld_spawns', 2266),
  ('2026_08_08_00_map_openworld_spawns', 2278),
  ('2026_08_08_00_map_openworld_spawns', 2282),
  ('2026_08_08_00_map_openworld_spawns', 2284),
  ('2026_08_08_00_map_openworld_spawns', 2285),
  ('2026_08_08_00_map_openworld_spawns', 2286),
  ('2026_08_08_00_map_openworld_spawns', 2287),
  ('2026_08_08_00_map_openworld_spawns', 2289),
  ('2026_08_08_00_map_openworld_spawns', 2290),
  ('2026_08_08_00_map_openworld_spawns', 2291),
  ('2026_08_08_00_map_openworld_spawns', 2293),
  ('2026_08_08_00_map_openworld_spawns', 2294),
  ('2026_08_08_00_map_openworld_spawns', 2296),
  ('2026_08_08_00_map_openworld_spawns', 2299),
  ('2026_08_08_00_map_openworld_spawns', 2300),
  ('2026_08_08_00_map_openworld_spawns', 2303),
  ('2026_08_08_00_map_openworld_spawns', 2304),
  ('2026_08_08_00_map_openworld_spawns', 2305),
  ('2026_08_08_00_map_openworld_spawns', 2308),
  ('2026_08_08_00_map_openworld_spawns', 2354),
  ('2026_08_08_00_map_openworld_spawns', 2356),
  ('2026_08_08_00_map_openworld_spawns', 2360),
  ('2026_08_08_00_map_openworld_spawns', 2362),
  ('2026_08_08_00_map_openworld_spawns', 2363),
  ('2026_08_08_00_map_openworld_spawns', 2371),
  ('2026_08_08_00_map_openworld_spawns', 2375),
  ('2026_08_08_00_map_openworld_spawns', 2441),
  ('2026_08_08_00_map_openworld_spawns', 2450),
  ('2026_08_08_00_map_openworld_spawns', 2451),
  ('2026_08_08_00_map_openworld_spawns', 2464),
  ('2026_08_08_00_map_openworld_spawns', 2465),
  ('2026_08_08_00_map_openworld_spawns', 2471),
  ('2026_08_08_00_map_openworld_spawns', 2481),
  ('2026_08_08_00_map_openworld_spawns', 2504),
  ('2026_08_08_00_map_openworld_spawns', 2515),
  ('2026_08_08_00_map_openworld_spawns', 2516),
  ('2026_08_08_00_map_openworld_spawns', 2519),
  ('2026_08_08_00_map_openworld_spawns', 2520),
  ('2026_08_08_00_map_openworld_spawns', 2521),
  ('2026_08_08_00_map_openworld_spawns', 2522),
  ('2026_08_08_00_map_openworld_spawns', 2526),
  ('2026_08_08_00_map_openworld_spawns', 2527),
  ('2026_08_08_00_map_openworld_spawns', 2549),
  ('2026_08_08_00_map_openworld_spawns', 2556),
  ('2026_08_08_00_map_openworld_spawns', 2559),
  ('2026_08_08_00_map_openworld_spawns', 2569),
  ('2026_08_08_00_map_openworld_spawns', 2574),
  ('2026_08_08_00_map_openworld_spawns', 2579),
  ('2026_08_08_00_map_openworld_spawns', 2582),
  ('2026_08_08_00_map_openworld_spawns', 2583),
  ('2026_08_08_00_map_openworld_spawns', 2586),
  ('2026_08_08_00_map_openworld_spawns', 2587),
  ('2026_08_08_00_map_openworld_spawns', 2590),
  ('2026_08_08_00_map_openworld_spawns', 2593),
  ('2026_08_08_00_map_openworld_spawns', 2594),
  ('2026_08_08_00_map_openworld_spawns', 2595),
  ('2026_08_08_00_map_openworld_spawns', 2597),
  ('2026_08_08_00_map_openworld_spawns', 2598),
  ('2026_08_08_00_map_openworld_spawns', 2599),
  ('2026_08_08_00_map_openworld_spawns', 2600),
  ('2026_08_08_00_map_openworld_spawns', 2614),
  ('2026_08_08_00_map_openworld_spawns', 2625),
  ('2026_08_08_00_map_openworld_spawns', 2634),
  ('2026_08_08_00_map_openworld_spawns', 2635),
  ('2026_08_08_00_map_openworld_spawns', 2639),
  ('2026_08_08_00_map_openworld_spawns', 2644),
  ('2026_08_08_00_map_openworld_spawns', 2645),
  ('2026_08_08_00_map_openworld_spawns', 2648),
  ('2026_08_08_00_map_openworld_spawns', 2649),
  ('2026_08_08_00_map_openworld_spawns', 2651),
  ('2026_08_08_00_map_openworld_spawns', 2652),
  ('2026_08_08_00_map_openworld_spawns', 2653),
  ('2026_08_08_00_map_openworld_spawns', 2654),
  ('2026_08_08_00_map_openworld_spawns', 2657),
  ('2026_08_08_00_map_openworld_spawns', 2660),
  ('2026_08_08_00_map_openworld_spawns', 2661),
  ('2026_08_08_00_map_openworld_spawns', 2662),
  ('2026_08_08_00_map_openworld_spawns', 2664),
  ('2026_08_08_00_map_openworld_spawns', 2669),
  ('2026_08_08_00_map_openworld_spawns', 2679),
  ('2026_08_08_00_map_openworld_spawns', 2680),
  ('2026_08_08_00_map_openworld_spawns', 2681),
  ('2026_08_08_00_map_openworld_spawns', 2682),
  ('2026_08_08_00_map_openworld_spawns', 2683),
  ('2026_08_08_00_map_openworld_spawns', 2684),
  ('2026_08_08_00_map_openworld_spawns', 2685),
  ('2026_08_08_00_map_openworld_spawns', 2686),
  ('2026_08_08_00_map_openworld_spawns', 2687),
  ('2026_08_08_00_map_openworld_spawns', 2688),
  ('2026_08_08_00_map_openworld_spawns', 2689),
  ('2026_08_08_00_map_openworld_spawns', 2690),
  ('2026_08_08_00_map_openworld_spawns', 2692),
  ('2026_08_08_00_map_openworld_spawns', 2699),
  ('2026_08_08_00_map_openworld_spawns', 2710),
  ('2026_08_08_00_map_openworld_spawns', 2713),
  ('2026_08_08_00_map_openworld_spawns', 2716),
  ('2026_08_08_00_map_openworld_spawns', 2767),
  ('2026_08_08_00_map_openworld_spawns', 2768),
  ('2026_08_08_00_map_openworld_spawns', 2769),
  ('2026_08_08_00_map_openworld_spawns', 2773),
  ('2026_08_08_00_map_openworld_spawns', 2774),
  ('2026_08_08_00_map_openworld_spawns', 2776),
  ('2026_08_08_00_map_openworld_spawns', 2779),
  ('2026_08_08_00_map_openworld_spawns', 2792),
  ('2026_08_08_00_map_openworld_spawns', 2803),
  ('2026_08_08_00_map_openworld_spawns', 2805),
  ('2026_08_08_00_map_openworld_spawns', 2810),
  ('2026_08_08_00_map_openworld_spawns', 2811),
  ('2026_08_08_00_map_openworld_spawns', 2813),
  ('2026_08_08_00_map_openworld_spawns', 2815),
  ('2026_08_08_00_map_openworld_spawns', 2819),
  ('2026_08_08_00_map_openworld_spawns', 2825),
  ('2026_08_08_00_map_openworld_spawns', 2826),
  ('2026_08_08_00_map_openworld_spawns', 2827),
  ('2026_08_08_00_map_openworld_spawns', 2828),
  ('2026_08_08_00_map_openworld_spawns', 2830),
  ('2026_08_08_00_map_openworld_spawns', 2831),
  ('2026_08_08_00_map_openworld_spawns', 2836),
  ('2026_08_08_00_map_openworld_spawns', 2849),
  ('2026_08_08_00_map_openworld_spawns', 2859),
  ('2026_08_08_00_map_openworld_spawns', 2874),
  ('2026_08_08_00_map_openworld_spawns', 2907),
  ('2026_08_08_00_map_openworld_spawns', 2912),
  ('2026_08_08_00_map_openworld_spawns', 2913),
  ('2026_08_08_00_map_openworld_spawns', 2915),
  ('2026_08_08_00_map_openworld_spawns', 2923),
  ('2026_08_08_00_map_openworld_spawns', 2928),
  ('2026_08_08_00_map_openworld_spawns', 2930),
  ('2026_08_08_00_map_openworld_spawns', 2933),
  ('2026_08_08_00_map_openworld_spawns', 2939),
  ('2026_08_08_00_map_openworld_spawns', 2950),
  ('2026_08_08_00_map_openworld_spawns', 2951),
  ('2026_08_08_00_map_openworld_spawns', 2952),
  ('2026_08_08_00_map_openworld_spawns', 2953),
  ('2026_08_08_00_map_openworld_spawns', 2961),
  ('2026_08_08_00_map_openworld_spawns', 2962),
  ('2026_08_08_00_map_openworld_spawns', 2963),
  ('2026_08_08_00_map_openworld_spawns', 2964),
  ('2026_08_08_00_map_openworld_spawns', 2965),
  ('2026_08_08_00_map_openworld_spawns', 2966),
  ('2026_08_08_00_map_openworld_spawns', 2972),
  ('2026_08_08_00_map_openworld_spawns', 2979),
  ('2026_08_08_00_map_openworld_spawns', 3003),
  ('2026_08_08_00_map_openworld_spawns', 3009),
  ('2026_08_08_00_map_openworld_spawns', 3014),
  ('2026_08_08_00_map_openworld_spawns', 3022),
  ('2026_08_08_00_map_openworld_spawns', 3029),
  ('2026_08_08_00_map_openworld_spawns', 3074);

DROP PROCEDURE IF EXISTS `rps_openworld_assert_scope`;
DELIMITER //
CREATE PROCEDURE `rps_openworld_assert_scope`()
BEGIN
  IF (
    SELECT COUNT(*)
    FROM `rps_openworld_spawn_target_map`
    WHERE `migration_version` = '2026_08_08_00_map_openworld_spawns'
  ) <> 539 THEN
    SIGNAL SQLSTATE '45000'
      SET MESSAGE_TEXT = 'RPS openworld spawn migration target-map scope mismatch';
  END IF;
END//
DELIMITER ;
CALL `rps_openworld_assert_scope`();
DROP PROCEDURE `rps_openworld_assert_scope`;

START TRANSACTION;

-- Snapshot before every destructive/update operation. INSERT IGNORE preserves
-- the first baseline when apply is run more than once with this input SHA.
INSERT IGNORE INTO `rps_openworld_creature_spawn_snapshot`
  (`migration_version`, `guid`, `map_id`, `spawn_difficulties`)
SELECT '2026_08_08_00_map_openworld_spawns', c.`guid`, c.`map`, c.`spawnDifficulties`
FROM `creature` c
JOIN `rps_openworld_spawn_target_map` m
  ON m.`migration_version` = '2026_08_08_00_map_openworld_spawns' AND m.`map_id` = c.`map`
WHERE c.`spawnDifficulties` <> '0';

INSERT IGNORE INTO `rps_openworld_gameobject_spawn_snapshot`
  (`migration_version`, `guid`, `map_id`, `spawn_difficulties`)
SELECT '2026_08_08_00_map_openworld_spawns', g.`guid`, g.`map`, g.`spawnDifficulties`
FROM `gameobject` g
JOIN `rps_openworld_spawn_target_map` m
  ON m.`migration_version` = '2026_08_08_00_map_openworld_spawns' AND m.`map_id` = g.`map`
WHERE g.`spawnDifficulties` <> '0';

INSERT IGNORE INTO `rps_openworld_areatrigger_spawn_snapshot`
  (`migration_version`, `spawn_id`, `map_id`, `spawn_difficulties`)
SELECT '2026_08_08_00_map_openworld_spawns', a.`SpawnId`, a.`MapId`, a.`SpawnDifficulties`
FROM `areatrigger` a
JOIN `rps_openworld_spawn_target_map` m
  ON m.`migration_version` = '2026_08_08_00_map_openworld_spawns' AND m.`map_id` = a.`MapId`
WHERE a.`SpawnDifficulties` <> '0';

-- Template difficulty 0 is copied from the lowest difficulty present on an
-- affected spawn when possible, otherwise from the template's lowest non-zero
-- row. No template ScriptName/AIName or loot-table row is edited.
INSERT IGNORE INTO `rps_openworld_template_difficulty_snapshot`
  (`migration_version`, `entry`, `source_difficulty_id`, `source_kind`, `created_difficulty_zero`)
SELECT
  '2026_08_08_00_map_openworld_spawns',
  affected.`entry`,
  CASE
    WHEN EXISTS (
      SELECT 1 FROM `creature_template_difficulty` zero_row
      WHERE zero_row.`Entry` = affected.`entry` AND zero_row.`DifficultyID` = 0
    ) THEN 0
    ELSE COALESCE(
      (
        SELECT MIN(matched.`DifficultyID`)
        FROM `creature_template_difficulty` matched
        JOIN `creature` matched_creature
          ON matched_creature.`id` = affected.`entry`
        JOIN `rps_openworld_spawn_target_map` matched_map
          ON matched_map.`migration_version` = '2026_08_08_00_map_openworld_spawns'
         AND matched_map.`map_id` = matched_creature.`map`
        WHERE matched.`Entry` = affected.`entry`
          AND matched.`DifficultyID` <> 0
          AND FIND_IN_SET(CAST(matched.`DifficultyID` AS CHAR), REPLACE(matched_creature.`spawnDifficulties`, ' ', '')) > 0
      ),
      (
        SELECT MIN(fallback_row.`DifficultyID`)
        FROM `creature_template_difficulty` fallback_row
        WHERE fallback_row.`Entry` = affected.`entry` AND fallback_row.`DifficultyID` <> 0
      )
    )
  END,
  CASE
    WHEN EXISTS (
      SELECT 1 FROM `creature_template_difficulty` zero_row
      WHERE zero_row.`Entry` = affected.`entry` AND zero_row.`DifficultyID` = 0
    ) THEN 'already_difficulty_0'
    WHEN EXISTS (
      SELECT 1
      FROM `creature_template_difficulty` matched
      JOIN `creature` matched_creature
        ON matched_creature.`id` = affected.`entry`
      JOIN `rps_openworld_spawn_target_map` matched_map
        ON matched_map.`migration_version` = '2026_08_08_00_map_openworld_spawns'
       AND matched_map.`map_id` = matched_creature.`map`
      WHERE matched.`Entry` = affected.`entry`
        AND matched.`DifficultyID` <> 0
        AND FIND_IN_SET(CAST(matched.`DifficultyID` AS CHAR), REPLACE(matched_creature.`spawnDifficulties`, ' ', '')) > 0
    ) THEN 'matching_spawn_difficulty'
    WHEN EXISTS (
      SELECT 1 FROM `creature_template_difficulty` fallback_row
      WHERE fallback_row.`Entry` = affected.`entry` AND fallback_row.`DifficultyID` <> 0
    ) THEN 'fallback_lowest_template_difficulty'
    ELSE 'missing_template_difficulty'
  END,
  CASE
    WHEN EXISTS (
      SELECT 1 FROM `creature_template_difficulty` zero_row
      WHERE zero_row.`Entry` = affected.`entry` AND zero_row.`DifficultyID` = 0
    ) THEN 0
    WHEN EXISTS (
      SELECT 1 FROM `creature_template_difficulty` fallback_row
      WHERE fallback_row.`Entry` = affected.`entry` AND fallback_row.`DifficultyID` <> 0
    ) THEN 1
    ELSE 0
  END
FROM (
  SELECT DISTINCT c.`id` AS `entry`
  FROM `creature` c
  JOIN `rps_openworld_spawn_target_map` m
    ON m.`migration_version` = '2026_08_08_00_map_openworld_spawns' AND m.`map_id` = c.`map`
) affected;

INSERT INTO `creature_template_difficulty` (
  `Entry`, `DifficultyID`, `LevelScalingDeltaMin`, `LevelScalingDeltaMax`, `ContentTuningID`,
  `HealthScalingExpansion`, `HealthModifier`, `ManaModifier`, `ArmorModifier`, `DamageModifier`,
  `CreatureDifficultyID`, `TypeFlags`, `TypeFlags2`, `TypeFlags3`, `LootID`, `PickPocketLootID`,
  `SkinLootID`, `GoldMin`, `GoldMax`, `StaticFlags1`, `StaticFlags2`, `StaticFlags3`,
  `StaticFlags4`, `StaticFlags5`, `StaticFlags6`, `StaticFlags7`, `StaticFlags8`, `VerifiedBuild`
)
SELECT
  source.`Entry`, 0, source.`LevelScalingDeltaMin`, source.`LevelScalingDeltaMax`, source.`ContentTuningID`,
  source.`HealthScalingExpansion`, source.`HealthModifier`, source.`ManaModifier`, source.`ArmorModifier`, source.`DamageModifier`,
  source.`CreatureDifficultyID`, source.`TypeFlags`, source.`TypeFlags2`, source.`TypeFlags3`, source.`LootID`, source.`PickPocketLootID`,
  source.`SkinLootID`, source.`GoldMin`, source.`GoldMax`, source.`StaticFlags1`, source.`StaticFlags2`, source.`StaticFlags3`,
  source.`StaticFlags4`, source.`StaticFlags5`, source.`StaticFlags6`, source.`StaticFlags7`, source.`StaticFlags8`, source.`VerifiedBuild`
FROM `creature_template_difficulty` source
JOIN `rps_openworld_template_difficulty_snapshot` snapshot
  ON snapshot.`migration_version` = '2026_08_08_00_map_openworld_spawns'
 AND snapshot.`entry` = source.`Entry`
 AND snapshot.`source_difficulty_id` = source.`DifficultyID`
WHERE snapshot.`created_difficulty_zero` = 1
  AND NOT EXISTS (
    SELECT 1
    FROM `creature_template_difficulty` zero_row
    WHERE zero_row.`Entry` = source.`Entry` AND zero_row.`DifficultyID` = 0
  );

UPDATE `creature` c
JOIN `rps_openworld_spawn_target_map` m
  ON m.`migration_version` = '2026_08_08_00_map_openworld_spawns' AND m.`map_id` = c.`map`
SET c.`spawnDifficulties` = '0'
WHERE c.`spawnDifficulties` <> '0';

UPDATE `gameobject` g
JOIN `rps_openworld_spawn_target_map` m
  ON m.`migration_version` = '2026_08_08_00_map_openworld_spawns' AND m.`map_id` = g.`map`
SET g.`spawnDifficulties` = '0'
WHERE g.`spawnDifficulties` <> '0';

UPDATE `areatrigger` a
JOIN `rps_openworld_spawn_target_map` m
  ON m.`migration_version` = '2026_08_08_00_map_openworld_spawns' AND m.`map_id` = a.`MapId`
SET a.`SpawnDifficulties` = '0'
WHERE a.`SpawnDifficulties` <> '0';

-- Instance boss-state group records are invalid on MAP_COMMON. Archive their
-- exact rows and remove only records whose instance map is in the frozen scope.
INSERT IGNORE INTO `rps_openworld_instance_spawn_group_snapshot`
  (`migration_version`, `instance_map_id`, `boss_state_id`, `boss_states`, `spawn_group_id`, `flags`)
SELECT '2026_08_08_00_map_openworld_spawns', i.`instanceMapId`, i.`bossStateId`, i.`bossStates`, i.`spawnGroupId`, i.`flags`
FROM `instance_spawn_groups` i
JOIN `rps_openworld_spawn_target_map` m
  ON m.`migration_version` = '2026_08_08_00_map_openworld_spawns' AND m.`map_id` = i.`instanceMapId`;

DELETE i
FROM `instance_spawn_groups` i
JOIN `rps_openworld_spawn_target_map` m
  ON m.`migration_version` = '2026_08_08_00_map_openworld_spawns' AND m.`map_id` = i.`instanceMapId`;

-- Manual groups become permanently active only when every resolvable member is
-- on a target map. Mixed/system/unresolved groups remain untouched and are
-- retained in the audit table for explicit operator review.
INSERT IGNORE INTO `rps_openworld_manual_spawn_group_audit` (
  `migration_version`, `group_id`, `group_name`, `original_group_flags`,
  `target_member_count`, `non_target_member_count`, `unresolved_member_count`,
  `eligible_for_auto_enable`
)
SELECT
  '2026_08_08_00_map_openworld_spawns', grouped.`group_id`, grouped.`group_name`, grouped.`group_flags`,
  grouped.`target_member_count`, grouped.`non_target_member_count`, grouped.`unresolved_member_count`,
  CASE
    WHEN grouped.`target_member_count` > 0
     AND grouped.`non_target_member_count` = 0
     AND grouped.`unresolved_member_count` = 0
     AND (grouped.`group_flags` & 1) = 0 THEN 1
    ELSE 0
  END
FROM (
  SELECT
    sgt.`groupId` AS `group_id`,
    sgt.`groupName` AS `group_name`,
    sgt.`groupFlags` AS `group_flags`,
    SUM(CASE WHEN target_map.`map_id` IS NOT NULL THEN 1 ELSE 0 END) AS `target_member_count`,
    SUM(CASE WHEN COALESCE(c.`map`, g.`map`) IS NOT NULL AND target_map.`map_id` IS NULL THEN 1 ELSE 0 END) AS `non_target_member_count`,
    SUM(CASE WHEN COALESCE(c.`map`, g.`map`) IS NULL THEN 1 ELSE 0 END) AS `unresolved_member_count`
  FROM `spawn_group_template` sgt
  JOIN `spawn_group` sg ON sg.`groupId` = sgt.`groupId`
  LEFT JOIN `creature` c ON sg.`spawnType` = 0 AND c.`guid` = sg.`spawnId`
  LEFT JOIN `gameobject` g ON sg.`spawnType` = 1 AND g.`guid` = sg.`spawnId`
  LEFT JOIN `rps_openworld_spawn_target_map` target_map
    ON target_map.`migration_version` = '2026_08_08_00_map_openworld_spawns'
   AND target_map.`map_id` = COALESCE(c.`map`, g.`map`)
  WHERE (sgt.`groupFlags` & 4) <> 0
  GROUP BY sgt.`groupId`, sgt.`groupName`, sgt.`groupFlags`
) grouped;

INSERT IGNORE INTO `rps_openworld_spawn_group_template_snapshot`
  (`migration_version`, `group_id`, `group_flags`)
SELECT '2026_08_08_00_map_openworld_spawns', audit.`group_id`, audit.`original_group_flags`
FROM `rps_openworld_manual_spawn_group_audit` audit
WHERE audit.`migration_version` = '2026_08_08_00_map_openworld_spawns'
  AND audit.`eligible_for_auto_enable` = 1;

UPDATE `spawn_group_template` sgt
JOIN `rps_openworld_spawn_group_template_snapshot` snapshot
  ON snapshot.`migration_version` = '2026_08_08_00_map_openworld_spawns' AND snapshot.`group_id` = sgt.`groupId`
SET sgt.`groupFlags` = snapshot.`group_flags` & ~4;

-- LoadLinkedRespawn rejects every link touching a non-instanceable map.
INSERT IGNORE INTO `rps_openworld_linked_respawn_archive`
  (`migration_version`, `guid`, `linked_guid`, `link_type`)
SELECT '2026_08_08_00_map_openworld_spawns', lr.`guid`, lr.`linkedGuid`, lr.`linkType`
FROM `linked_respawn` lr
LEFT JOIN `creature` slave_creature
  ON lr.`linkType` IN (0, 1) AND slave_creature.`guid` = lr.`guid`
LEFT JOIN `gameobject` slave_gameobject
  ON lr.`linkType` IN (2, 3) AND slave_gameobject.`guid` = lr.`guid`
LEFT JOIN `creature` master_creature
  ON lr.`linkType` IN (0, 3) AND master_creature.`guid` = lr.`linkedGuid`
LEFT JOIN `gameobject` master_gameobject
  ON lr.`linkType` IN (1, 2) AND master_gameobject.`guid` = lr.`linkedGuid`
LEFT JOIN `rps_openworld_spawn_target_map` slave_creature_map
  ON slave_creature_map.`migration_version` = '2026_08_08_00_map_openworld_spawns'
 AND slave_creature_map.`map_id` = slave_creature.`map`
LEFT JOIN `rps_openworld_spawn_target_map` slave_gameobject_map
  ON slave_gameobject_map.`migration_version` = '2026_08_08_00_map_openworld_spawns'
 AND slave_gameobject_map.`map_id` = slave_gameobject.`map`
LEFT JOIN `rps_openworld_spawn_target_map` master_creature_map
  ON master_creature_map.`migration_version` = '2026_08_08_00_map_openworld_spawns'
 AND master_creature_map.`map_id` = master_creature.`map`
LEFT JOIN `rps_openworld_spawn_target_map` master_gameobject_map
  ON master_gameobject_map.`migration_version` = '2026_08_08_00_map_openworld_spawns'
 AND master_gameobject_map.`map_id` = master_gameobject.`map`
WHERE slave_creature_map.`map_id` IS NOT NULL
   OR slave_gameobject_map.`map_id` IS NOT NULL
   OR master_creature_map.`map_id` IS NOT NULL
   OR master_gameobject_map.`map_id` IS NOT NULL;

DELETE lr
FROM `linked_respawn` lr
JOIN `rps_openworld_linked_respawn_archive` archived
  ON archived.`migration_version` = '2026_08_08_00_map_openworld_spawns'
 AND archived.`guid` = lr.`guid`
 AND archived.`link_type` = lr.`linkType`;

INSERT INTO `rps_openworld_spawn_migration`
  (`migration_version`, `input_sha256`, `target_map_count`)
VALUES ('2026_08_08_00_map_openworld_spawns', '87de10705bf297e9b9cd7b3b0a34f11ca2277f7caabb1f193fe17f398a92c528', 539)
ON DUPLICATE KEY UPDATE
  `input_sha256` = VALUES(`input_sha256`),
  `target_map_count` = VALUES(`target_map_count`);

COMMIT;

-- Preflight: every count below must be zero after the matching MapDifficulty(0)
-- hotfix has been applied.
SELECT 'creature_nonzero_difficulty' AS `check_name`, COUNT(*) AS `violations`
FROM `creature` c
JOIN `rps_openworld_spawn_target_map` m
  ON m.`migration_version` = '2026_08_08_00_map_openworld_spawns' AND m.`map_id` = c.`map`
WHERE c.`spawnDifficulties` <> '0'
UNION ALL
SELECT 'gameobject_nonzero_difficulty', COUNT(*)
FROM `gameobject` g
JOIN `rps_openworld_spawn_target_map` m
  ON m.`migration_version` = '2026_08_08_00_map_openworld_spawns' AND m.`map_id` = g.`map`
WHERE g.`spawnDifficulties` <> '0'
UNION ALL
SELECT 'areatrigger_nonzero_difficulty', COUNT(*)
FROM `areatrigger` a
JOIN `rps_openworld_spawn_target_map` m
  ON m.`migration_version` = '2026_08_08_00_map_openworld_spawns' AND m.`map_id` = a.`MapId`
WHERE a.`SpawnDifficulties` <> '0'
UNION ALL
SELECT 'active_instance_spawn_groups', COUNT(*)
FROM `instance_spawn_groups` i
JOIN `rps_openworld_spawn_target_map` m
  ON m.`migration_version` = '2026_08_08_00_map_openworld_spawns' AND m.`map_id` = i.`instanceMapId`
UNION ALL
SELECT 'active_linked_respawn_touching_target', COUNT(*)
FROM `linked_respawn` lr
JOIN `rps_openworld_linked_respawn_archive` archived
  ON archived.`migration_version` = '2026_08_08_00_map_openworld_spawns'
 AND archived.`guid` = lr.`guid`
 AND archived.`link_type` = lr.`linkType`;

-- Review before production rollout; a missing source means the template had no
-- non-zero difficulty row to copy and needs a deliberately authored default.
SELECT `entry`, `source_kind`
FROM `rps_openworld_template_difficulty_snapshot`
WHERE `migration_version` = '2026_08_08_00_map_openworld_spawns'
  AND `source_kind` = 'missing_template_difficulty'
ORDER BY `entry`;

SELECT `group_id`, `group_name`, `target_member_count`, `non_target_member_count`, `unresolved_member_count`
FROM `rps_openworld_manual_spawn_group_audit`
WHERE `migration_version` = '2026_08_08_00_map_openworld_spawns'
  AND `eligible_for_auto_enable` = 0
ORDER BY `group_id`;
